files:
  include: 'src/**/*.s+(a|c)ss'
options:
  max-warnings: 1
  merge-default-rules: true
rules:
  indentation:
    - 2
    - size: 4
  class-name-format:
    - 2
    - convention: hyphenatedbem
  force-pseudo-nesting:
    - 0